---
title: "Introduction to Rcpp"
author: "James Henderson, PhD"
affiliation: "CSCAR Data Science Consultant"
date: "June 30, 2017"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Why use Rcpp?

### Performance

#### Speed
**R** is an intepreted, dynamically typed language making it inherently slower than
compiled, statically typed languages such as **C++** and **C**.  Vectorization
can take you a long way in **R**, but explicit loops written in **C/C++** can
be __easier to program and read__,  __several times faster__, and sometimes both.  

#### Memory
The primary use-case for Rcpp is to reduce computation time. Sometimes improvements
in speed come from being more intelligent about memory. At other times you may 
wish to work in a compiled language in order to exercise more control over how memory is
managed. This is not the focus of this
workshop, but something you should be aware of.

#### Warning
Many **R** functions and packages have already been optimized using compiled code
written by better **C/C++** than you or I. Use these when they are available. 
Don't reinvent the wheel unless wheel design is your focus!

#### Simplicity and Familiarity

As we will see, you don't need Rcpp to use compiled code within R.  However,
Rcpp makes it convenient to do so because:
  
  + **C++** can be programmed in an 'object-oriented' much like **R** making
    it easier to translate
    
  + **Rcpp** simplifies and partially automates linking **R** and **C++**
    
  + **Rcpp** automates many common conversions between native **R** and **C++** types

While compiled code can often provide substantial improvments in computation time,
these improvements should be balanced against the time it takes you to implement them.
**Rcpp** is convenient because it allows you to work primarily in **R** and incorporate **C++**
only when you encounter a bottleneck.

#### Access to **C++** libraries

A final reason to use **Rcpp** is to make use of exisiting computational libraries 
that do something useful.

    
## Installing Rcpp

Install the **R** package `Rcpp` using, i.e. `install.packages('Rcpp')`. If working
on a remote server you may first need to point *R* to the location of your package 
library, i.e. `.libPaths('~/Rlib')`.

To use locally, you will need a C++ compiler such as `gcc`, `g++` or `clang`.  
Mac users should install Xcode from the app store.  

## Calling C from R

Before delving into Rcpp, let's do a quick review of how to call compiled **C** code
from **R**.

<a href='./CallingCfromR.html'>Calling C from R</a>

## Using Rcpp

### Rcpp references

  + <a href="http://www.rcpp.org/">Home page</a>

  + <a href="https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-quickref.pdf">Quick reference card</a>
  
  + Hadley Wickham's Rcpp <a href="http://adv-r.had.co.nz/Rcpp.html">tutorial</a>

### C++ references

Rcpp provides a number of variable types similar to familiar **R** and the quick
reference above is a good place to start.  Below are a few references for learning
more **C++** as you go along:

  + <a href="http://www.cplusplus.com/doc/tutorial/">Cplusplus.com<a>
  + <a href="https://www.tutorialspoint.com/cplusplus/">Tutorial Point</a>

You should focus intitially on standard types, along with the classes and
associated methods from the standard library (STL or "std").

### Using C++ libraries

C++ object classes and associated methods are defined using templates. 
These templates are generally defined in header files ending in `.h`.  For our
purposes the most important of these is: `Rcpp.h`.  To have access to the classes
defined in header files you "include" them: `#include <Rcpp.h>`.

Just as with `R` packages, we can disambiguate the source definition of a specific class
using two colons `Rcpp::IntegerVector` or `std::vector<int>`.  

### Prototyping with sourceCpp

When prototyping straightforward Rcpp functions you can use `sourceCpp()` to 
quickly compile and link **C++** functions into and active **R** session. 

Be sure to:

0. Use `#include <Rcpp.h>` to link against the Rcpp library.
1. Include `// [[Rcpp::export]]` tags to make functions visible to **R**.
2. Create tests to check that your functions work as expected.

#### Example 1

<a href='./Example1.html'>Example 1: sourceCpp()</a>

#### Example 2
Our second example involves tabulating the observed transitions from a finite
state Markov chain. It is based on the scripts below:

  + <a href='./MarkovExample.R'>MarkovExample.R</a>
  + <a href='./simObs.cpp'>simObs.cpp</a>
  + <a href='./countTransitions.cpp'>countTransitions.cpp</a>

#### Error checking and exceptions 
It is good programing practice to do some error checking at the start of a
function to ensure that values passed using arguments conform to expectations. 

In **R** we often use `stop('Error message')` to raise exceptions and report errors.
In **C++** you can use the key-word `throw` with an error type such as `std::range_error('message')`
for the same purpose.  

With Rcpp there is also a shortcut function `Rcpp::stop("message about error")`. 

See this <a href='http://gallery.rcpp.org/articles/intro-to-exceptions/'> link </a>
for more on exception-handling. 

#### Printing to the console

While it is generally recommended to use a debugging tool to find errors in code,
I often debug by hand using messages printed to the console. This can be done 
using the `Rcpp::Rcout` variable:

```
#include <Rcpp.h>
using namespace Rcpp; 

// more code

  Rcout << "Print your mesage and maybe a variable: " << var << std::endl; 

// more code
```

### Using Rcpp in an R package

It is often worthwhile to organize the code
base for a project using an R package.  You can set up an empty R package use `devtools::create`.
To include Rcpp functions in an R package, place the **C++** source code in the `src` directory.
Before building or installing the package, use `Rcpp::compileAttributes()` to 
automatically generate wrappers that handle translations between **R** and **C++** types.

A common workflow in this instance would be:

  1. Modify one or more **C++** files.  
  2. If you've changed what gets passed to or from **R** call `Rcpp::compileAttributes('path/to/package/)`.
  3. Run `R CMD BUILD` and perhaps also `R CMD check` from the command line, or alternately
     `devtools::build('path/to/package')` from the console, to rebuild the package.  
  4. Go through some testing process to check your code.
  

